/**
 * data.js — Firebase writes + external fetches
 */
import { ref, set, push } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-database.js';
import {
  API_BASE, PIPED, RSS2JSON, MU_CHANNEL, HIGHLIGHT_IDS, DEFAULT_INJURIES, FIXTURES,
  STORAGE_KEY, NICK_KEY
} from './constants.js';
import { S } from './state.js';
import {
  parseFixtureDate, isMatchFinished, toYmd, normalizeName, namesMatch, isManUnited, resultFor
} from './domain.js';

export async function postPrediction(fid,mu,opp,text){const nick=(localStorage.getItem(NICK_KEY)||'Fan').slice(0,24);const payload={type:'prediction',nick,mu:+mu,opp:+opp,text:(text||'').trim().slice(0,200),ts:Date.now()};if(S.discussRef){await push(ref(S.db,`discuss/${fid}`),payload)}else{const key=String(fid);S.discussions[key]=S.discussions[key]||[];S.discussions[key].push(payload)}}

export async function saveData(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(S.records))}catch(_){}if(S.recordsRef)await set(S.recordsRef,S.records)}
export async function searchHighlights(f){const queries=[`${f.opp} v Man Utd | Highlights`,`Man Utd v ${f.opp} | Highlights`,`Manchester United vs ${f.opp} Highlights`];for(const q of queries){try{const res=await fetch(`${PIPED}/search?q=${encodeURIComponent(q)}&filter=videos`);if(!res.ok)continue;const data=await res.json();const items=data.items||data||[];const streams=items.filter(it=>it.type==='stream'||(it.url||'').includes('watch'));const scored=streams.map(it=>{const id=(it.url||'').split('v=')[1]||it.id;const title=(it.title||'').toLowerCase(),up=(it.uploaderName||'').toLowerCase(),upUrl=it.uploaderUrl||'';let score=0;if(up.includes('manchester united')||upUrl.includes(MU_CHANNEL))score+=50;if(up.includes('nbc')||up.includes('sky sports')||up.includes('premier league'))score+=40;if(title.includes('highlight'))score+=30;if(title.includes('extended'))score+=5;if(title.includes('matchday live')||title.includes('build-up')||title.includes('pre-match')||title.includes('post-match interview'))score-=60;if(normalizeName(title).includes(normalizeName(f.opp)))score+=20;if(it.duration&&it.duration>=180&&it.duration<=1200)score+=15;if(it.duration&&it.duration>1800)score-=40;if(it.duration&&it.duration<120)score-=20;return{id,title:it.title,score}}).filter(x=>x.id).sort((a,b)=>b.score-a.score);if(scored[0]&&scored[0].score>=30){const best=scored[0],extended=scored.find(s=>s.id!==best.id&&/extended/i.test(s.title));return{id:best.id,extended:extended?.id||null}}}catch(_){}}return null}
export async function autoImportResults(){if(S.autoImportDone)return;S.autoImportDone=true;const today=new Date();today.setHours(23,59,59,999);const toCheck=FIXTURES.filter(f=>{const rec=S.records[f.id]||S.records[String(f.id)];return!(rec&&rec.mu!==undefined)&&isMatchFinished(f)});if(!toCheck.length){for(const f of FIXTURES){const key=String(f.id),rec=S.records[key];if(!rec||rec.mu===undefined)continue;const known=HIGHLIGHT_IDS[f.id];if(known&&(!rec.videoId||rec.videoId!==known.id)){rec.videoId=known.id;rec.videoExtended=known.extended||null;try{await saveData()}catch(_){}}}return}let changed=false;for(const fixture of toCheck){try{const d=parseFixtureDate(fixture.date);const ymd=toYmd(d);const res=await fetch(`${API_BASE}/scoreboard?dates=${ymd}`);if(!res.ok)continue;const data=await res.json();const events=data.events||[];for(const ev of events){const comps=ev.competitions||[];for(const c of comps){const competitors=c.competitors||[];let mu=null,opp=null;for(const t of competitors){if(isManUnited(t.team))mu=t;else opp=t}if(!mu||!opp)continue;const muHome=mu.homeAway==='home';const muScore=+mu.score,oppScore=+opp.score,oppName=opp.team?.displayName||opp.team?.name||fixture.opp;if(Number.isNaN(muScore)||Number.isNaN(oppScore))continue;const key=String(fixture.id);if(S.records[key]?.mu!==undefined)continue;const known=HIGHLIGHT_IDS[fixture.id];const hlText=fixture.venue==='H'?`Full time · Man United ${muScore}–${oppScore} ${oppName}.`:`Full time · ${oppName} ${oppScore}–${muScore} Man United.`;S.records[key]={mu:muScore,opp:oppScore,auto:true,highlight:hlText,videoId:known?.id||null,videoExtended:known?.extended||null};changed=true}}}catch(e){console.warn(e)}}for(const f of FIXTURES){const key=String(f.id),rec=S.records[key];if(!rec||rec.mu===undefined)continue;const known=HIGHLIGHT_IDS[f.id];if(known){if(rec.videoId!==known.id||(known.extended&&rec.videoExtended!==known.extended)){rec.videoId=known.id;rec.videoExtended=known.extended||null;changed=true}}else if(!rec.videoId){const found=await searchHighlights(f);if(found){rec.videoId=found.id;rec.videoExtended=found.extended;changed=true}}}if(changed){try{await saveData()}catch(_){}}}
export async function fetchStandings(){try{const res=await fetch(`${API_BASE}/standings?season=2026`);if(!res.ok)return;const data=await res.json();const entries=data?.children?.[0]?.standings?.entries||[];S.standings=entries.map(e=>{const stats={};(e.stats||[]).forEach(s=>{stats[s.name]=s.displayValue});return{name:e.team?.displayName||e.team?.name||'?',rank:+stats.rank||0,p:+stats.gamesPlayed||0,gd:+stats.pointDifferential||0,pts:+stats.points||0,isMu:isManUnited(e.team)}}).sort((a,b)=>a.rank-b.rank);S.muTable=S.standings.find(s=>s.isMu)||null}catch(e){console.warn(e)}}
export async function fetchNews(next){const queries=[];if(next){queries.push(`Manchester United ${next.opp} when:14d`);queries.push(`"Man United" OR "Manchester United" preview ${next.opp} when:14d`)}queries.push('Manchester United team news when:7d');const items=[],seen=new Set();for(const q of queries){try{const rss=`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-GB&gl=GB&ceid=GB:en`;const res=await fetch(RSS2JSON+encodeURIComponent(rss));if(!res.ok)continue;const data=await res.json();for(const it of(data.items||[]).slice(0,6)){const title=it.title||'';if(seen.has(title))continue;seen.add(title);let src=it.author||'',clean=title;const dash=title.lastIndexOf(' - ');if(dash>0){src=title.slice(dash+3);clean=title.slice(0,dash)}items.push({title:clean,link:it.link,source:src,date:it.pubDate})}}catch(e){console.warn(e)}if(items.length>=8)break}S.newsItems=items.slice(0,8)}

export async function seedInjuries(){if(S.injuriesRef){try{await set(S.injuriesRef,DEFAULT_INJURIES)}catch(_){}}}
