/**
 * ui-buildup.js — news, injuries, standings, next fixture helpers
 */
import { FIXTURES } from './constants.js';
import { S } from './state.js';
import { escapeHtml, parseFixtureDate } from './domain.js';

export function nextUnplayed(){return FIXTURES.find(f=>{const rec=S.records[f.id]||S.records[String(f.id)];return!(rec&&rec.mu!==undefined)})||null}
export function ordinal(n){const s=['th','st','nd','rd'],v=n%100;return s[(v-20)%10]||s[v]||s[0]}
export function buildupNotes(next){if(!next)return['Season complete.'];const d=parseFixtureDate(next.date),now=new Date();now.setHours(0,0,0,0);const days=Math.round((d-now)/86400000),home=next.venue==='H',notes=[];if(days<0)notes.push(`GW${next.gw} vs ${next.opp} — score import pending.`);else if(days===0)notes.push(`Matchday · ${home?'Old Trafford':'Away'} vs ${next.opp}.`);else if(days===1)notes.push('MD-1: taper · set-piece walkthrough.');else if(days<=3)notes.push(`MD-${days}: recovery then shape vs ${next.opp}.`);else notes.push(`${days} days until ${home?'home':'away'} vs ${next.opp}.`);if(S.muTable)notes.push(`Table: ${S.muTable.rank}${ordinal(S.muTable.rank)} · ${S.muTable.pts} pts · GD ${S.muTable.gd>=0?'+':''}${S.muTable.gd}.`);const outs=(S.injuries.players||[]).filter(p=>p.status==='out').map(p=>p.name);if(outs.length)notes.push('Out: '+outs.join(', ')+'.');return notes}
export function renderNews(){if(!S.newsItems.length)return`<div class="panel wide"><h2>Matchday news</h2><div style="color:var(--grey);font-size:12px">Loading headlines…</div></div>`;return`<div class="panel wide"><h2>Matchday news & build-up</h2><ul class="news-list">${S.newsItems.map(n=>`<li><a href="${escapeHtml(n.link)}" target="_blank" rel="noopener">${escapeHtml(n.title)}</a><span class="src">${escapeHtml(n.source||'News')}${n.date?' · '+new Date(n.date).toLocaleDateString():''}</span></li>`).join('')}</ul></div>`}
export function renderInjuries(){const list=(S.injuries.players||[]).map(p=>{const badge=p.status==='out'?'out':p.status==='doubt'?'doubt':'ok';const label=p.status==='out'?'Out':p.status==='doubt'?'Doubt':'OK';return`<li><span class="player">${escapeHtml(p.name)}</span><span class="badge ${badge}">${label}</span><span class="reason">${escapeHtml(p.reason)}${p.return&&p.return!=='TBC'?' · ~'+escapeHtml(p.return):''}${p.note?' — '+escapeHtml(p.note):''}</span></li>`}).join('');return`<div class="panel"><h2>Squad availability</h2><ul class="injury-list">${list}</ul><a class="src-link" href="${escapeHtml(S.injuries.source||'#')}" target="_blank" rel="noopener">Premier Injuries · ${escapeHtml(S.injuries.updated||'')}</a></div>`}
export function renderBuildup(){const next=nextUnplayed(),notes=buildupNotes(next);const tableRows=S.standings.slice(0,8).map(s=>`<tr class="${s.isMu?'mu':''}"><td class="pos">${s.rank}</td><td>${escapeHtml(s.name)}${s.isMu?' ★':''}</td><td class="num">${s.p}</td><td class="num">${s.gd>=0?'+':''}${s.gd}</td><td class="pts">${s.pts}</td></tr>`).join('');let extra='';if(S.muTable&&S.muTable.rank>8)extra=`<tr class="mu"><td class="pos">${S.muTable.rank}</td><td>${escapeHtml(S.muTable.name)} ★</td><td class="num">${S.muTable.p}</td><td class="num">${S.muTable.gd>=0?'+':''}${S.muTable.gd}</td><td class="pts">${S.muTable.pts}</td></tr>`;return`<div class="buildup"><div class="panel"><h2>Premier League table</h2>${S.standings.length?`<table class="standings-table"><thead><tr><th class="pos">#</th><th>Club</th><th class="num">P</th><th class="num">GD</th><th class="pts">Pts</th></tr></thead><tbody>${tableRows}${extra}</tbody></table>`:`<div style="color:var(--grey);font-size:12px">Loading…</div>`}</div><div class="panel"><h2>Matchday build-up</h2>${next?`<div class="next-match-line">Next · GW${next.gw} vs ${escapeHtml(next.opp)}</div><div class="next-meta">${escapeHtml(next.date)} · ${next.venue==='H'?'Home':'Away'} · ${next.comp}</div>`:`<div class="next-match-line">No fixtures left</div>`}<ul class="buildup-notes">${notes.map(n=>`<li>${escapeHtml(n)}</li>`).join('')}</ul></div>${renderInjuries()}${renderNews()}</div>`}
