/**
 * ui-fans.js — video banner + fan dialog
 */
import { S } from './state.js';
import { escapeHtml, ytThumb, ytWatch, ytSearchUrl, defaultBannerSvg } from './domain.js';
import { NICK_KEY, HIGHLIGHT_IDS, FIXTURES } from './constants.js';

export function videoBanner(f,rec){const id=rec?.videoId||HIGHLIGHT_IDS[f.id]?.id;const extended=rec?.videoExtended||HIGHLIGHT_IDS[f.id]?.extended;const href=id?ytWatch(id):ytSearchUrl(f);const img=id?ytThumb(id):defaultBannerSvg();return`<a class="vid-banner" href="${href}" target="_blank" rel="noopener"><img src="${img}" alt="Highlights" loading="lazy" onerror="this.src='${defaultBannerSvg()}'"/><div class="play"><div class="circle">▶</div><span>${id?'Watch highlights':'Find highlights'}</span></div></a><div class="vid-links"><a href="${href}" target="_blank" rel="noopener">Open on YouTube</a>${extended?`<a href="${ytWatch(extended)}" target="_blank" rel="noopener">Extended</a>`:''}<a href="${ytSearchUrl(f)}" target="_blank" rel="noopener">More results</a></div>`}
export function fanCount(fid){const a=S.discussions[String(fid)]||[];const b=S.discussions[fid]||[];return new Set([...(a.map(x=>x.id||JSON.stringify(x))),...(b.map(x=>x.id||JSON.stringify(x)))]).size||Math.max(a.length,b.length)}
export function fanIconBtn(f){const n=fanCount(f.id);return`<button type="button" class="fan-btn" data-open-fan="${f.id}" title="Fans">${n?'💬':(S.records[f.id]||S.records[String(f.id)])?.mu!==undefined?'💬':'🎯'}${n?`<span class="cnt">${n}</span>`:''}</button>`}
export function renderDialog(){if(S.openDialogFid==null)return'';const f=FIXTURES.find(x=>x.id===S.openDialogFid);if(!f)return'';const rec=S.records[f.id]||S.records[String(f.id)];const played=rec&&rec.mu!==undefined;const list=[...(S.discussions[String(f.id)]||[]),...(S.discussions[f.id]||[])].slice().reverse();const seen=new Set();const dedup=[];for(const c of list){const k=c.id||`${c.nick}|${c.ts}|${c.type}`;if(seen.has(k))continue;seen.add(k);dedup.push(c)}const nick=localStorage.getItem(NICK_KEY)||'';const preds=dedup.filter(c=>c.type==='prediction'||(c.mu!==undefined&&c.opp!==undefined&&c.type!=='comment'));const comments=dedup.filter(c=>c.type==='comment'||(c.type!=='prediction'&&c.mu===undefined));const items=played?[...preds,...comments]:preds;const tag=f.comp==='UCL'?`UCL MD${f.md}`:`GW${f.gw}`;const title=played?`Reckoning · ${tag}`:`Predict · ${tag}`;const sub=`Man United ${f.venue==='H'?'vs':'@'} ${f.opp}`;let listHtml='';if(!items.length)listHtml=`<div class="empty">${played?'No predictions or comments yet.':'No predictions yet — set the scoreline.'}</div>`;else listHtml=items.map(c=>{if(c.type==='prediction'||(c.mu!==undefined&&c.opp!==undefined&&c.type!=='comment'))return`<div class="comment"><span class="who">${escapeHtml(c.nick||'Fan')}</span><span class="when">${c.ts?new Date(c.ts).toLocaleString():''}</span><div><span class="pred-score">${c.mu} – ${c.opp}</span>${c.text?' · '+escapeHtml(c.text):''}</div></div>`;return`<div class="comment"><span class="who">${escapeHtml(c.nick||'Fan')}</span><span class="when">${c.ts?new Date(c.ts).toLocaleString():''}</span><div>${escapeHtml(c.text||'')}</div></div>`}).join('');const form=played?`<form id="fan-dialog-form" data-fid="${f.id}" data-mode="comment"><input name="nick" maxlength="24" placeholder="Your name" value="${escapeHtml(nick)}" required/><input name="text" maxlength="400" placeholder="Comment on the game..." required/><button type="submit">Post comment</button></form>`:`<form id="fan-dialog-form" data-fid="${f.id}" data-mode="prediction"><input name="nick" maxlength="24" placeholder="Your name" value="${escapeHtml(nick)}" required/><div class="pred-row"><span class="mu-mono">MUFC</span><input type="number" name="mu" min="0" max="20" placeholder="-" required/><span>:</span><input type="number" name="opp" min="0" max="20" placeholder="-" required/><span class="mu-mono">${escapeHtml(f.opp).slice(0,4).toUpperCase()}</span></div><input name="text" maxlength="200" placeholder="Optional note (e.g. MotM, scoreline theory)"/><button type="submit">Lock prediction</button></form>`;return`<div class="modal-backdrop" id="fan-modal"><div class="modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h3>${title}</h3><div class="sub">${escapeHtml(sub)}</div></div><button type="button" class="modal-close" id="fan-modal-close" aria-label="Close">×</button></div><div class="modal-body">${listHtml}</div><div class="modal-foot">${form}</div></div></div>`}
